[package]
name = "revi"
version = "0.0.0-beta-0.3"
authors = ["cowboy8625 <cowboy8625@protonmail.com>"]
edition = "2018"
description = "A Terminal Based Vim Inspired Text Editor"
readme = "README.md"
repository = "https://github.com/revi-editor/revi"
license-file = "LICENSE"
keywords = ["text-editor", "command-line", "termainl", "vim", "editor", "configuration"]
categories = ["text-editors", "text-processing", "command-line-utilities", "command-line-interface"]



[dependencies]
mlua = { version = "0.6.0-beta.3", features = ["lua53", "vendored"] }
clap = "2.33.3"
ropey = "1.2.0"
crossterm = "0.20.0"
itertools = "0.10.0"

