[package]
name = "revi-core"
version = "0.0.0-beta-0.6"
authors = ["cowboy8625 <cowboy8625@protonmail.com>"]
edition = "2018"
description = "The core of revi text-editor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
mlua = { version = "0.6.0-beta.3", features = ["lua53", "vendored"] }
ropey = "1.3.1"
unicode-width = "0.1.8"
unicode-segmentation = "1.7.1"
revi-ui = { path = "../revi-ui", version="0.0.0-beta-0.6"}

[features]
debug_bar = []
debug_line = []
debug_line_words = []
debug_input_number = []
